server:
  port: 8083
  ssl:
    key-store: .keystore
    key-store-password: 123456
    key-store-type: JKS
    key-alias: tomcat
spring:
    datasource:
        name: mysql_test
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat
          driver-class-name: com.mysql.jdbc.Driver
          #基本属性
          url: jdbc:mysql://localhost:3306/crud_test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: root
          password: root
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20
    thymeleaf:
     #缓冲的配置
        cache: false
        check-template: true
        check-template-location: true
        #开启MVC thymeleaf 视图解析
        enabled: true
        encoding: utf-8
        mode: LEGACYHTML5
        prefix: classpath:/templates/
        suffix: .html
    aop:
      auto: true
      proxy-target-class: true
    servlet:
          multipart:
            max-file-size: 10Mb
            max-request-size: 100Mb
#邮件发送配置
    mail:
      host: smtp.qq.com
      username: 982084398@qq.com
      password: zmgkoyruvtfzbfjd
      default-encoding: utf-8
      properties:
        main:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true
#sql打印
logging:
  level:
   code.mapper: DEBUG
#swagger是否开启
swagger:
  show: true
#配置mybatis扫描位置
mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
